//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailySync.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://servicios.adsef.pr.gov/CIMA_WAPI/api/Proveedores/getProveedores")]
        public string ProveedoresCuidoGetProvUrl {
            get {
                return ((string)(this["ProveedoresCuidoGetProvUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQL2012;Initial Catalog=CompassDb;Integrated Security=True")]
        public string CompassDbConnString {
            get {
                return ((string)(this["CompassDbConnString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://servicios.adsef.pr.gov/CIMA_WAPI/api/Proveedores/getProveedoresById/{0}")]
        public string ProveedoresCuidoGetProvByIdTemplateUrl {
            get {
                return ((string)(this["ProveedoresCuidoGetProvByIdTemplateUrl"]));
            }
            set {
                this["ProveedoresCuidoGetProvByIdTemplateUrl"] = value;
            }
        }
    }
}
