//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailySync.PanEstablishmentsWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PanEstablishmentsWS.wsEstablishmentsSoap")]
    public interface wsEstablishmentsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getEstablishments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DailySync.PanEstablishmentsWS.OBJ_Establishment[] getEstablishments(string status, string establishment, string municipality);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OBJ_Establishment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int estIdField;
        
        private string estNameField;
        
        private string estTrackingNumberField;
        
        private string estAuthNumberField;
        
        private string estStatusCodeField;
        
        private string estStatusField;
        
        private string estBusinessTypeField;
        
        private System.DateTime estOpeningDateField;
        
        private string estLegalStructureField;
        
        private string estRegionField;
        
        private string estMunicipalityField;
        
        private string estUnitNumberField;
        
        private bool estChainField;
        
        private bool estFranchiseField;
        
        private string estPhone1Field;
        
        private int estPhoneType1Field;
        
        private string estPhone2Field;
        
        private int estPhoneType2Field;
        
        private string estEmailField;
        
        private string estAddPostal1Field;
        
        private string estAddPostal2Field;
        
        private string estAddPostalCityField;
        
        private string estAddPostalStateField;
        
        private string estAddPostalZipCodeField;
        
        private string estAddPhysical1Field;
        
        private string estAddPhysical2Field;
        
        private string estAddPhysicalNeighborhoodField;
        
        private string estAddPhysicalStreetField;
        
        private string estAddPhysicalKilometerField;
        
        private string estAddPhysicalCityField;
        
        private string estAddPhysicalStateField;
        
        private string estAddPhysicalZipCodeField;
        
        private string estAddAdditionalInfoField;
        
        private string estLatLongField;
        
        private string estLatestModField;
        
        private OBJ_EstablishmentOtherData oEstablishmentOtherDataField;
        
        private OBJ_EstablishmentService[] oEstablishmentServiceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int estId {
            get {
                return this.estIdField;
            }
            set {
                this.estIdField = value;
                this.RaisePropertyChanged("estId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string estName {
            get {
                return this.estNameField;
            }
            set {
                this.estNameField = value;
                this.RaisePropertyChanged("estName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string estTrackingNumber {
            get {
                return this.estTrackingNumberField;
            }
            set {
                this.estTrackingNumberField = value;
                this.RaisePropertyChanged("estTrackingNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string estAuthNumber {
            get {
                return this.estAuthNumberField;
            }
            set {
                this.estAuthNumberField = value;
                this.RaisePropertyChanged("estAuthNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string estStatusCode {
            get {
                return this.estStatusCodeField;
            }
            set {
                this.estStatusCodeField = value;
                this.RaisePropertyChanged("estStatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string estStatus {
            get {
                return this.estStatusField;
            }
            set {
                this.estStatusField = value;
                this.RaisePropertyChanged("estStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string estBusinessType {
            get {
                return this.estBusinessTypeField;
            }
            set {
                this.estBusinessTypeField = value;
                this.RaisePropertyChanged("estBusinessType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime estOpeningDate {
            get {
                return this.estOpeningDateField;
            }
            set {
                this.estOpeningDateField = value;
                this.RaisePropertyChanged("estOpeningDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string estLegalStructure {
            get {
                return this.estLegalStructureField;
            }
            set {
                this.estLegalStructureField = value;
                this.RaisePropertyChanged("estLegalStructure");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string estRegion {
            get {
                return this.estRegionField;
            }
            set {
                this.estRegionField = value;
                this.RaisePropertyChanged("estRegion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string estMunicipality {
            get {
                return this.estMunicipalityField;
            }
            set {
                this.estMunicipalityField = value;
                this.RaisePropertyChanged("estMunicipality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string estUnitNumber {
            get {
                return this.estUnitNumberField;
            }
            set {
                this.estUnitNumberField = value;
                this.RaisePropertyChanged("estUnitNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool estChain {
            get {
                return this.estChainField;
            }
            set {
                this.estChainField = value;
                this.RaisePropertyChanged("estChain");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool estFranchise {
            get {
                return this.estFranchiseField;
            }
            set {
                this.estFranchiseField = value;
                this.RaisePropertyChanged("estFranchise");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string estPhone1 {
            get {
                return this.estPhone1Field;
            }
            set {
                this.estPhone1Field = value;
                this.RaisePropertyChanged("estPhone1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int estPhoneType1 {
            get {
                return this.estPhoneType1Field;
            }
            set {
                this.estPhoneType1Field = value;
                this.RaisePropertyChanged("estPhoneType1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string estPhone2 {
            get {
                return this.estPhone2Field;
            }
            set {
                this.estPhone2Field = value;
                this.RaisePropertyChanged("estPhone2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int estPhoneType2 {
            get {
                return this.estPhoneType2Field;
            }
            set {
                this.estPhoneType2Field = value;
                this.RaisePropertyChanged("estPhoneType2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string estEmail {
            get {
                return this.estEmailField;
            }
            set {
                this.estEmailField = value;
                this.RaisePropertyChanged("estEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string estAddPostal1 {
            get {
                return this.estAddPostal1Field;
            }
            set {
                this.estAddPostal1Field = value;
                this.RaisePropertyChanged("estAddPostal1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string estAddPostal2 {
            get {
                return this.estAddPostal2Field;
            }
            set {
                this.estAddPostal2Field = value;
                this.RaisePropertyChanged("estAddPostal2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string estAddPostalCity {
            get {
                return this.estAddPostalCityField;
            }
            set {
                this.estAddPostalCityField = value;
                this.RaisePropertyChanged("estAddPostalCity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string estAddPostalState {
            get {
                return this.estAddPostalStateField;
            }
            set {
                this.estAddPostalStateField = value;
                this.RaisePropertyChanged("estAddPostalState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string estAddPostalZipCode {
            get {
                return this.estAddPostalZipCodeField;
            }
            set {
                this.estAddPostalZipCodeField = value;
                this.RaisePropertyChanged("estAddPostalZipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string estAddPhysical1 {
            get {
                return this.estAddPhysical1Field;
            }
            set {
                this.estAddPhysical1Field = value;
                this.RaisePropertyChanged("estAddPhysical1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string estAddPhysical2 {
            get {
                return this.estAddPhysical2Field;
            }
            set {
                this.estAddPhysical2Field = value;
                this.RaisePropertyChanged("estAddPhysical2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string estAddPhysicalNeighborhood {
            get {
                return this.estAddPhysicalNeighborhoodField;
            }
            set {
                this.estAddPhysicalNeighborhoodField = value;
                this.RaisePropertyChanged("estAddPhysicalNeighborhood");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string estAddPhysicalStreet {
            get {
                return this.estAddPhysicalStreetField;
            }
            set {
                this.estAddPhysicalStreetField = value;
                this.RaisePropertyChanged("estAddPhysicalStreet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string estAddPhysicalKilometer {
            get {
                return this.estAddPhysicalKilometerField;
            }
            set {
                this.estAddPhysicalKilometerField = value;
                this.RaisePropertyChanged("estAddPhysicalKilometer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string estAddPhysicalCity {
            get {
                return this.estAddPhysicalCityField;
            }
            set {
                this.estAddPhysicalCityField = value;
                this.RaisePropertyChanged("estAddPhysicalCity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string estAddPhysicalState {
            get {
                return this.estAddPhysicalStateField;
            }
            set {
                this.estAddPhysicalStateField = value;
                this.RaisePropertyChanged("estAddPhysicalState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string estAddPhysicalZipCode {
            get {
                return this.estAddPhysicalZipCodeField;
            }
            set {
                this.estAddPhysicalZipCodeField = value;
                this.RaisePropertyChanged("estAddPhysicalZipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string estAddAdditionalInfo {
            get {
                return this.estAddAdditionalInfoField;
            }
            set {
                this.estAddAdditionalInfoField = value;
                this.RaisePropertyChanged("estAddAdditionalInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string estLatLong {
            get {
                return this.estLatLongField;
            }
            set {
                this.estLatLongField = value;
                this.RaisePropertyChanged("estLatLong");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string estLatestMod {
            get {
                return this.estLatestModField;
            }
            set {
                this.estLatestModField = value;
                this.RaisePropertyChanged("estLatestMod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public OBJ_EstablishmentOtherData oEstablishmentOtherData {
            get {
                return this.oEstablishmentOtherDataField;
            }
            set {
                this.oEstablishmentOtherDataField = value;
                this.RaisePropertyChanged("oEstablishmentOtherData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=36)]
        public OBJ_EstablishmentService[] oEstablishmentService {
            get {
                return this.oEstablishmentServiceField;
            }
            set {
                this.oEstablishmentServiceField = value;
                this.RaisePropertyChanged("oEstablishmentService");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OBJ_EstablishmentOtherData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private bool openAllyearField;
        
        private bool openJanuaryField;
        
        private bool openFebruaryField;
        
        private bool openMarchField;
        
        private bool openAprilField;
        
        private bool openMayField;
        
        private bool openJuneField;
        
        private bool openJulyField;
        
        private bool openAugustField;
        
        private bool openSeptemberField;
        
        private bool openOctoberField;
        
        private bool openNovemberField;
        
        private bool openDecemberField;
        
        private bool open24HoursField;
        
        private string open24HoursCommentField;
        
        private string employeeAmountField;
        
        private string cashRegisterAmountField;
        
        private bool scannersField;
        
        private bool wICAuthorizedField;
        
        private string wICidField;
        
        private bool wICDeniedField;
        
        private string wICDeniedReasonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool openAllyear {
            get {
                return this.openAllyearField;
            }
            set {
                this.openAllyearField = value;
                this.RaisePropertyChanged("openAllyear");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool openJanuary {
            get {
                return this.openJanuaryField;
            }
            set {
                this.openJanuaryField = value;
                this.RaisePropertyChanged("openJanuary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool openFebruary {
            get {
                return this.openFebruaryField;
            }
            set {
                this.openFebruaryField = value;
                this.RaisePropertyChanged("openFebruary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool openMarch {
            get {
                return this.openMarchField;
            }
            set {
                this.openMarchField = value;
                this.RaisePropertyChanged("openMarch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool openApril {
            get {
                return this.openAprilField;
            }
            set {
                this.openAprilField = value;
                this.RaisePropertyChanged("openApril");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool openMay {
            get {
                return this.openMayField;
            }
            set {
                this.openMayField = value;
                this.RaisePropertyChanged("openMay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool openJune {
            get {
                return this.openJuneField;
            }
            set {
                this.openJuneField = value;
                this.RaisePropertyChanged("openJune");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool openJuly {
            get {
                return this.openJulyField;
            }
            set {
                this.openJulyField = value;
                this.RaisePropertyChanged("openJuly");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool openAugust {
            get {
                return this.openAugustField;
            }
            set {
                this.openAugustField = value;
                this.RaisePropertyChanged("openAugust");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool openSeptember {
            get {
                return this.openSeptemberField;
            }
            set {
                this.openSeptemberField = value;
                this.RaisePropertyChanged("openSeptember");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool openOctober {
            get {
                return this.openOctoberField;
            }
            set {
                this.openOctoberField = value;
                this.RaisePropertyChanged("openOctober");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool openNovember {
            get {
                return this.openNovemberField;
            }
            set {
                this.openNovemberField = value;
                this.RaisePropertyChanged("openNovember");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool openDecember {
            get {
                return this.openDecemberField;
            }
            set {
                this.openDecemberField = value;
                this.RaisePropertyChanged("openDecember");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool open24Hours {
            get {
                return this.open24HoursField;
            }
            set {
                this.open24HoursField = value;
                this.RaisePropertyChanged("open24Hours");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string open24HoursComment {
            get {
                return this.open24HoursCommentField;
            }
            set {
                this.open24HoursCommentField = value;
                this.RaisePropertyChanged("open24HoursComment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string employeeAmount {
            get {
                return this.employeeAmountField;
            }
            set {
                this.employeeAmountField = value;
                this.RaisePropertyChanged("employeeAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string cashRegisterAmount {
            get {
                return this.cashRegisterAmountField;
            }
            set {
                this.cashRegisterAmountField = value;
                this.RaisePropertyChanged("cashRegisterAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public bool scanners {
            get {
                return this.scannersField;
            }
            set {
                this.scannersField = value;
                this.RaisePropertyChanged("scanners");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public bool WICAuthorized {
            get {
                return this.wICAuthorizedField;
            }
            set {
                this.wICAuthorizedField = value;
                this.RaisePropertyChanged("WICAuthorized");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string WICid {
            get {
                return this.wICidField;
            }
            set {
                this.wICidField = value;
                this.RaisePropertyChanged("WICid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public bool WICDenied {
            get {
                return this.wICDeniedField;
            }
            set {
                this.wICDeniedField = value;
                this.RaisePropertyChanged("WICDenied");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string WICDeniedReason {
            get {
                return this.wICDeniedReasonField;
            }
            set {
                this.wICDeniedReasonField = value;
                this.RaisePropertyChanged("WICDeniedReason");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OBJ_EstablishmentService : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serviceCode_FKField;
        
        private int establishment_FKField;
        
        private bool selectedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string serviceCode_FK {
            get {
                return this.serviceCode_FKField;
            }
            set {
                this.serviceCode_FKField = value;
                this.RaisePropertyChanged("serviceCode_FK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int establishment_FK {
            get {
                return this.establishment_FKField;
            }
            set {
                this.establishment_FKField = value;
                this.RaisePropertyChanged("establishment_FK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool selected {
            get {
                return this.selectedField;
            }
            set {
                this.selectedField = value;
                this.RaisePropertyChanged("selected");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsEstablishmentsSoapChannel : DailySync.PanEstablishmentsWS.wsEstablishmentsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsEstablishmentsSoapClient : System.ServiceModel.ClientBase<DailySync.PanEstablishmentsWS.wsEstablishmentsSoap>, DailySync.PanEstablishmentsWS.wsEstablishmentsSoap {
        
        public wsEstablishmentsSoapClient() {
        }
        
        public wsEstablishmentsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsEstablishmentsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsEstablishmentsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsEstablishmentsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DailySync.PanEstablishmentsWS.OBJ_Establishment[] getEstablishments(string status, string establishment, string municipality) {
            return base.Channel.getEstablishments(status, establishment, municipality);
        }
    }
}
